# Turso Setup Helper Script for Weekplanner
Write-Host "=== Turso SQLite Setup for Weekplanner ===" -ForegroundColor Cyan
Write-Host ""

# Check if Turso CLI is installed
try {
    $tursoVersion = turso --version 2>&1
    Write-Host "✓ Turso CLI is installed: $tursoVersion" -ForegroundColor Green
} catch {
    Write-Host "✗ Turso CLI not found. Installing..." -ForegroundColor Yellow
    irm get.turso.tech/install.ps1 | iex
    Write-Host "✓ Turso CLI installed!" -ForegroundColor Green
}

Write-Host ""
Write-Host "Step 1: Authenticate with Turso" -ForegroundColor Cyan
Write-Host "This will open a browser window to sign in..."
turso auth login

Write-Host ""
Write-Host "Step 2: Creating database 'weekplanner-db'..." -ForegroundColor Cyan
try {
    turso db create weekplanner-db 2>&1 | Out-Null
    Write-Host "✓ Database created!" -ForegroundColor Green
} catch {
    Write-Host "Note: Database might already exist, continuing..." -ForegroundColor Yellow
}

Write-Host ""
Write-Host "Step 3: Getting database URL..." -ForegroundColor Cyan
$dbUrl = turso db show weekplanner-db --url
Write-Host "Database URL: $dbUrl" -ForegroundColor Green

Write-Host ""
Write-Host "Step 4: Creating auth token..." -ForegroundColor Cyan
$token = turso db tokens create weekplanner-db
Write-Host "Token created!" -ForegroundColor Green

Write-Host ""
Write-Host "Step 5: Writing .env file..." -ForegroundColor Cyan
$envContent = @"
# Turso/libsql configuration
# Auto-generated by setup-turso.ps1
VITE_LIBSQL_URL=$dbUrl
VITE_LIBSQL_TOKEN=$token
"@

$envPath = Join-Path $PSScriptRoot ".env"
$envContent | Out-File -FilePath $envPath -Encoding UTF8
Write-Host "✓ .env file created at: $envPath" -ForegroundColor Green

Write-Host ""
Write-Host "=== Setup Complete! ===" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "1. Run: npm run dev" -ForegroundColor White
Write-Host "   Your localStorage data will auto-migrate to Turso!" -ForegroundColor Gray
Write-Host ""
Write-Host "2. For GitHub Pages, add these secrets to your repo:" -ForegroundColor White
Write-Host "   Go to: Settings → Secrets and variables → Actions" -ForegroundColor Gray
Write-Host "   Add secret: VITE_LIBSQL_URL = $dbUrl" -ForegroundColor Gray
Write-Host "   Add secret: VITE_LIBSQL_TOKEN = $token" -ForegroundColor Gray
Write-Host ""
Write-Host "Press any key to exit..."
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
